services:
  mcp-bridge:
    build:
      context: .
    develop:
      watch:
        - path: mcp_bridge
          action: rebuild
    container_name: mcp-bridge

    ports:
      - "9093:9093"
    environment:
      - MCP_BRIDGE__CONFIG__FILE=config.json
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./config.json:/mcp_bridge/config.json
      - ../servers:/servers
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

